config/routes.rb
Rails.application.routes.draw do
  resources :surveyors, only: :show
  resources :surveys, only: :show
  resources :projects, only: :show
  resources :survey_seasons, only: :show
  resources :stations, only: :show
  resources :visits, only: :show
  resources :historic_visits, only: :show
  resources :locations, only: :show
  resources :captures, only: :show do
    member do
      get 'comparisons'
    end
  end
  resources :historic_captures, only: :show do
    member do
      get 'comparisons'
    end
  end
  resources :capture_images, only: :show
  resources :location_images, only: :show
  get 'search', to: 'application#search', as: "search"
  get 'map', to: 'application#map', as: 'map'
end

app/models/location_image.rb
class LocationImage < Image
  validates :image_owner_type, inclusion: { in: ['Location', 'Visit','Station'] }
end

app/controllers/location_images_controller.rb
class LocationImagesController < ApplicationController

  #see comments in the set_current_nodes method of the application controller
  before_filter :set_current_tree_node

  def show
    @location_image = LocationImage.find(params[:id])
    respond_to do |format|
      format.html { render 'show' }
      format.js { render 'show' }
    end
  end

  def set_current_tree_node
    if params.has_key?(:id) && (location_image=LocationImage.find_by_id(params[:id]))
      parent = location_image.image_owner
      session[:current_tree_node]=parent.class.name+'_'+parent.id.to_s
      session[:current_tree_node_type] = parent.class.name
      session[:current_tree_node_id] = parent.id.to_s
    end
  end

end

app/views/location_images/_location_image.html.erb
<%= content_tag :li, class: 'location_image_row thumbnail_container clearfix', id: "location_image_row_#{location_image.id}", title: location_image.display_name do -%>
	<%= content_tag :div, :class => "location_image_column thumbnail_img_container" do -%>
		<% if !location_image.image.nil? && location_image.file_present? %>
			<%= link_to(image_tag(location_image.image.thumb.url, alt: location_image.display_name, class: 'thumbnail_img', id: "LocationImage_#{location_image.id}" ), location_image_path(location_image.id))  %>
			<%=
			if (only_unsorted_are_moveable==true && location_image.image_owner_type!='Location') || only_unsorted_are_moveable==false
				content_tag :div, class: "drag_column" do
				  image_tag("move.png", alt: "drag-handle", title: "Drag to navigation tree to move the image", id: "LocationImage_#{location_image.id}_handle")
				end
			end
			 %>
		<% end %>
	<% end -%>
	<div class='thumbnail_caption_container'>
		<%= link_to location_image.display_name, location_image_path(location_image.id) %>
	</div>
<% end -%>

app/views/location_images/_location_images_grid.html.erb
<% only_unsorted_are_moveable = true if local_assigns[:only_unsorted_are_moveable].nil? %>
<% if location_images.empty? %>
	<p>There are no location images associated with this object</p>
<% else %>
	<ul class='thumbnails'>
	<%= render location_images, only_unsorted_are_moveable: only_unsorted_are_moveable  %>
	</ul>
<% end %>

app/views/location_images/show.html.erb
<%= render 'show_view_header' %>
<div class='data-pane-body'>
	<%= breadcrumb_div(@location_image, separator:  "<span class='icomoon-chevron-right'></span>", with_self: true).html_safe %>
	<% unless @location_image.file_present? %>
	<div class='alert alert-error long-path-container'>
		<h4>Image missing!</h4>
		<p>Looks like the file for this image is missing. This might happen if:
			<ul> <li>The file was moved/deleted/renamed with an external application (like Finder)</li>
				<li>You forgot to connect to the server</li>
			</ul>
		</p>

		<p>As a reminder, you should <strong>never</strong> move/delete/rename files with an application other than this one.</p>
		<p>If possible, locate <%= @location_image.image.file.filename %> and move it back to <%= @location_image.image.store_dir %></p>
		<p>(PS: If you see an image below, that doesn't mean the image exists. It's a preview of the full version)</p>
	</div>
	<% end %>
	<div class='row-fluid'>
		<div class='span12'>
			<%= image_tag(@location_image.image.medium.url, alt: @location_image.display_name) %>
		</div>
	</div>
	<dl class='dl-horizontal'>
		<dt><%= LocationImage.human_attribute_name(:file_name) %>:</dt><dd><%= @location_image.display_name%></dd>
		<dt><%= LocationImage.human_attribute_name(:file_size) %>:</dt><dd><%= show_value(number_to_human_size(@location_image.file_size))%></dd>
		<dt><%= LocationImage.human_attribute_name(:x_dim) %>:</dt><dd><%= show_value(@location_image.x_dim," px") %></dd>
		<dt><%= LocationImage.human_attribute_name(:y_dim) %>:</dt><dd><%= show_value(@location_image.y_dim," px") %></dd>
		<dt><%= LocationImage.human_attribute_name(:bit_depth) %>:</dt><dd><%= show_value(@location_image.bit_depth," bit") %></dd>
		<dt>Camera:</dt><dd id='camera_value'><%= show_value(@location_image.try(:camera).try(:display_name)) %></dd>
		<dt>Lens:</dt><dd id='lens_value'><%= show_value(@location_image.try(:lens).try(:display_name)) %></dd>
		<dt><%= LocationImage.human_attribute_name(:focal_length)%>:</dt><dd id='focal_length_value'><%= show_value(@location_image.focal_length.to_s,'mm') %></dd>
		<dt><%= LocationImage.human_attribute_name(:f_stop)%>:</dt><dd id='f_stop_value'><%= show_value(@location_image.f_stop,"f/",prepend: true) %></dd>
		<dt><%= LocationImage.human_attribute_name(:shutter_speed)%>:</dt><dd id='shutter_speed_value'><%= show_value(@location_image.shutter_speed.to_s,'sec') %></dd>
		<dt><%= LocationImage.human_attribute_name(:iso)%>:</dt><dd id='iso_value'><%= show_value(@location_image.iso.to_s) %></dd>
		<dt><%= LocationImage.human_attribute_name(:capture_datetime)%>:</dt><dd id='capture_datetime_value'><%= show_value(@location_image.capture_datetime) %></dd>
	</dl>
</div>