config/routes.rb
Rails.application.routes.draw do
  resources :surveyors, only: :show
  resources :surveys, only: :show
  resources :projects, only: :show
  resources :survey_seasons, only: :show
  resources :stations, only: :show
  resources :visits, only: :show
  resources :historic_visits, only: :show
  resources :locations, only: :show
  resources :captures, only: :show do
    member do
      get 'comparisons'
    end
  end
  resources :historic_captures, only: :show do
    member do
      get 'comparisons'
    end
  end
  resources :capture_images, only: :show
  resources :location_images, only: :show
  get 'search', to: 'application#search', as: "search"
  get 'map', to: 'application#map', as: 'map'
end

app/models/capture_image.rb
# == Schema Information
#
# Table name: capture_images
#
#  id               :integer          not null, primary key
#  captureable_id       :integer
#  hash_key         :string(255)
#  image :text
#  file_size        :float
#  x_dim            :integer
#  y_dim            :integer
#  bit_depth        :integer
#  image_state      :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class CaptureImage < ActiveRecord::Base
  include NumberHelper
  include ImageHelper
  include PgSearch

  multisearchable :against => [:image_state, :display_name]

  attr_accessible :captureable_id, :captureable_type, :bit_depth, :image, :image_remote, :file_size, :hash_key, :image_state, :x_dim, :y_dim, :remote, :image_secure_token, :comments, :legacy_path
  attr_accessible :image_cache, :do_not_save_metadata
  attr_accessor :do_not_save_metadata


  before_update :save_metadata, if: '!self.do_not_save_metadata'
  before_create :save_metadata, if: '!self.do_not_save_metadata'

  belongs_to :captureable, polymorphic: true
  alias :parent :captureable
  delegate :station, to: :captureable, allow_nil: true

  #see the resolution_similar? method for usage
  SIMILARITY_THRES = 0.3

  mount_uploader :image, ImageUploader

  mount_uploader :image_remote, ImageRemoteUploader


  validates :image_state, inclusion: { in: IMAGE_STATES }
  #validates :image, presence: true, if: 'self.new_record?'
  validates :captureable_type, inclusion: { in: ['Capture','HistoricCapture']}

  scope :remotely_uploaded, lambda { where.not(image_remote: [nil, '']) }
  #published aliases remotely_uploaded in the content of a capture image
  scope :published, lambda { remotely_uploaded }


  scope :not_processing, lambda { where(image_tmp: [nil, '']) }
  def file_present?
    if image.present?
      File.exists?(self.image.file.path)
    elsif image_tmp.present?
      true
    else
      false
    end
  end

  #we add a dynamic search column (display_name) in multisearchable
  #so we need to override the default pg_search rebuild with this
  #naive approach (slow)
  def self.rebuild_pg_search_documents
    find_each { |record| record.update_pg_search_document }
  end

  #used in comparisons when listing image files for capture/hcapture
  def image_listing_name
    return "#{self.image_state} - (#{self.x_dim}x#{self.y_dim}) - #{self.display_name}"
  end

  #read_attribute is used here to get the actual value
  #stored in the db row, rather than the mounted uploader object
  def display_name
    image_full_name = read_attribute("image")
    if image_full_name.present?
      image_full_name.sub("_"+self.image_secure_token, "")
    elsif image_tmp.present? && image_tmp=~/.*\/([^\/]+)$/
      $1
    else
      "UNKNOWN"
    end
  end

  def remote
    image_remote.present?
  end

  def remote=(remote_bool)
    remote_state = (remote_bool==true || remote_bool==1 || remote_bool=="1")
    #if the remote state changes, change image_remote (either add file or remove file)
    if (remote_state && !remote) || (!remote_state && remote)
      attribute_will_change!(:image_remote)
      config_for_remote_upload(remote_state)
    end
  end

  def save_metadata
    if File.exists?(self.image.file.path) || File.exists?(self.fs_path)
      begin
        path = File.exists?(self.image.file.path) ? self.image.file.path : self.fs_path
        @exif = MiniExiftool.new(path)
      rescue ArgumentError => e
        #with some files it miniexiftool throws an exception when there in invalid UTF-8 characters in the metadata
        if e.message == "invalid byte sequence in UTF-8"
          return true #silently fail.
        else
          raise e
        end
      end
    else
      return true #silently fail when file is missing
    end
    self.x_dim = @exif.file_type == "RAF" ?  @exif.raw_image_width : @exif.imagewidth
    self.y_dim = @exif.file_type == "RAF" ?  @exif.raw_image_height : @exif.imageheight
    self.bit_depth = @exif.bitspersample
    self.file_size = self.image.file.size
    if self.captureable_type=='Capture'
      capture = Capture.find_by_id(self.captureable_id)
      if !capture.nil? && (capture.capture_images.empty? || !capture.metadata_set?)
        update_hash = {}
        #exif can produce results as strings or as numerics. For us, it benefits to use both. By default, the miniexiftool will output string, so do this, then change to numerics
        if @exif.datetimeoriginal
          update_hash[:capture_datetime] = @exif.datetimeoriginal
        end
        update_hash[:shutter_speed] = (@exif.shutterspeed ||= @exif.exposuretime)
        update_hash[:shutter_speed] = update_hash[:shutter_speed].to_s #store as a string instead of a rational
        update_hash[:camera_make] = @exif.make
        update_hash[:camera_model] = @exif.model
        @exif.numerical = true
        @exif.reload
        update_hash[:iso] = @exif.iso
        update_hash[:f_stop] = @exif.aperture ||= @exif.fnumber
        update_hash[:focal_length] = @exif.focallength
        update_hash[:lat] = @exif.gpslatitude
        update_hash[:long] = @exif.gpslongitude
        update_hash[:elevation] = @exif.gpsaltitude
        capture.update_attributes(update_hash)
        true #return, even if the capture update fails, allowing  the capture image to be saved regardless of whether the capture update is successfully.
      end
    end
  end

  def aligned?(cap_img)
    if (x_dim==cap_img.x_dim && y_dim==cap_img.y_dim) || resolution_similar?(cap_img)
      return true
    else
      return false
    end
  end

  #Checks to see if the resolutions are similar
  def resolution_similar?(cap_img)
    return false if x_dim.blank? || y_dim.blank? || cap_img.blank? || cap_img.x_dim.blank? || cap_img.y_dim.blank?
    return SIMILARITY_THRES>(x_dim-cap_img.x_dim).abs/[x_dim,cap_img.x_dim].max.to_f*50 + (y_dim-cap_img.y_dim).abs/[y_dim,cap_img.y_dim].max.to_f*50
  end



end

app/controllers/capture_images_controller.rb
class CaptureImagesController < ApplicationController
  #see comments in the set_current_nodes method of the application controller
  before_filter :set_current_tree_node

  def show
    @capture_image = CaptureImage.find(params[:id])
    respond_to do |format|
      format.html { render 'show' }
      format.js { render 'show'}
    end
  end

  def set_current_tree_node
    if params.has_key?(:id) && (capture_image=CaptureImage.find_by_id(params[:id]))
      parent = capture_image.captureable
      session[:current_tree_node]=parent.class.name+'_'+parent.id.to_s
      session[:current_tree_node_type] = parent.class.name
      session[:current_tree_node_id] = parent.id.to_s
    end
  end

end

app/views/capture_images/_capture_image.html.erb
<%= content_tag :tr, class: 'capture_image_row', id: "capture_image_row_#{capture_image.id}" do -%>
	<%= content_tag :td, class: "drag_column" do -%>
		<%= image_tag("move.png", alt: "drag-handle", title: "Drag to navigation tree to move the image", id: "CaptureImage_#{capture_image.id}_handle") %>
	<% end -%>
	<%= content_tag :td, :class => "capture_image_column" do -%>
		<% if !capture_image.image.nil? && capture_image.file_present? %>
			<%= link_to(image_tag(capture_image.image.thumb.url, alt: capture_image.display_name, id: "CaptureImage_#{capture_image.id}" ), capture_image_path(capture_image.id))  %>
			<div><%= link_to capture_image.display_name, capture_image_path(capture_image.id) %></div>
		<% else %>
			<%= link_to capture_image.display_name, capture_image_path(capture_image.id)%>
		<% end %>
	<% end -%>
	<td class='image_column'><%= capture_image.image_state %></td>
	<td class='image_state_column'><%= capture_image.x_dim %></td>
	<td class='xdim_column'><%= capture_image.y_dim %></td>
	<td class='ydim_column'><%= number_to_human_size(capture_image.file_size) if !capture_image.file_size.nil? %></td>
	<td class='remote_column'><%= !capture_image.image_remote.blank? %></td>
<% end -%>

app/views/capture_images/_capture_images_table.html.erb
<% if capture.capture_images.empty? %>
	<p>There are no capture images associated with this capture</p>
<% else %>
	<h4 id='capture_images_header'><span class='icomoon-image'></span> Capture Images</h4>
	<table class='table table-striped' id='capture_images_table'>
	<tr class='column_header'>
		<th class='drag_column'></th>
		<th class='image_column'>Image</th>
		<th class='image_state_column'>Image State</th>
		<th class='xdim_column'>Width</th>
		<th class='ydim_column'>Height</th>
		<th class='file_size_column'>File Size</th>
		<th class='remote_column'>Remote?</th>
	</tr>
	<%= render capture.capture_images %>
	</table>
<% end %>

app/views/capture_images/show.html.erb
<%= render 'show_view_header' %>

<div class="data-pane-body">
	<%= breadcrumb_div(@capture_image, separator:  "<span class='icomoon-chevron-right'></span>", with_self: true).html_safe %>
	<% unless @capture_image.file_present? %>
	<div class='alert alert-error long-path-container'>
		<h4>Image missing!</h4>
		<p>Looks like the file for this image is missing. This might happen if:
		<ul> <li>The file was moved/deleted/renamed with an external application (like Finder)</li>
			 <li>You forgot to connect to the server</li>
		</ul>
		</p>

		<p>As a reminder, you should <strong>never</strong> move/delete/rename files with an application other than this one.</p>
		<p>If possible, locate <%= @capture_image.image.file.filename %> and move it back to <%= @capture_image.image.store_dir %></p>
		<p>(PS: If you see an image below, that doesn't mean the image exists. It's a preview of the full version)</p>
	</div>
	<% end %>
	<div class='row-fluid'>
		<div class='span12'>
		<%= image_tag(@capture_image.image.medium.url, alt: @capture_image.display_name) %>
		</div>
	</div>

	<dl class='dl-horizontal'>
		<dt><%= CaptureImage.human_attribute_name(:file_name) %>:</dt><dd><%= @capture_image.display_name%></dd>
		<dt><%= CaptureImage.human_attribute_name(:image_state) %>:</dt><dd><%= show_value(@capture_image.image_state)%></dd>
		<dt><%= CaptureImage.human_attribute_name(:file_size) %>:</dt><dd><%= show_value(number_to_human_size(@capture_image.file_size))%></dd>
		<dt><%= CaptureImage.human_attribute_name(:x_dim) %>:</dt><dd><%= show_value(@capture_image.x_dim," px") %></dd>
		<dt><%= CaptureImage.human_attribute_name(:y_dim) %>:</dt><dd><%= show_value(@capture_image.y_dim," px") %></dd>
		<dt><%= CaptureImage.human_attribute_name(:bit_depth) %>:</dt><dd><%= show_value(@capture_image.bit_depth," bit") %></dd>
		<dt><%= CaptureImage.human_attribute_name(:comments) %>:</dt><dd><%= show_value(@capture_image.comments)%></dd>
		<dt><%= CaptureImage.human_attribute_name(:remote) %>:</dt><dd><%= show_value(@capture_image.remote)%></dd>
	</dl>

</div>